custom: ["https://feevale.br/", "https://feevale.br/graduacao/jogos-digitais", "https://feevale.br/graduacao/ciencia-da-computacao", "https://www.feevale.br/institucional/infraestrutura/instituto-de-ciencias-criativas-e-tecnologicas"]
